# Generated by Django 4.2 on 2023-04-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=500)),
                ('name', models.CharField(default='', max_length=500)),
                ('profile', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
